version: "3.8"
services:
  mongodb:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile
    container_name: mongodb-rabbit-nest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - network-mongo-rabbit
  nginx-api-rabbit-consumers:
    build:
      context: ./nginx
    container_name: nginx-nest-rabbut
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - nginx-api-net
  rabbitmq:
    container_name: nestjs-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=daniel-admin
      - RABBITMQ_DEFAULT_PASS=daniel1234
networks:
  network-mongo-rabbit:
    driver: bridge
  nginx-api-net:
    driver: bridge
